### PR TITLE
Add Kapex Price to both menus (PanelFooter and TopBar)

### PR DESCRIPTION
**Pull request by jmontanholi**
# If in doubt on how to run these changes locally, these steps can be taken:
### 7. Inside `summitswap-interface` directory run `yarn start`
----------------------------------------
### - src/widgets/menu/components/PanelFooter

### CODE REVIEW

**Review by LukeSamkharadze — COMMENTED** [review]
Can you search up `kodaPriceUsd` and add `kapexPriceUsd` at the same places as well (in `test.tsx` and `stories.tsx`, for testing)?

**Comment by jmontanholi** [comment]
Pushed the requested changes to get-kapex-price on summitswap interface

**Comment by LukeSamkharadze** [comment]
@jmontanholi I meant in the UI-KIT

**Comment by jmontanholi** [comment]
Done, can you please check, I have some linters errors in my local repo, it says that `showConnectButton` is missing in type

**Review by LukeSamkharadze — COMMENTED** [review]
@jmontanholi tests are failing

**Comment by jmontanholi** [comment]
@LukeSamkharadze done, updated them.

**Review by LukeSamkharadze — APPROVED** [review]

**Pull request merged**
